import type { Metadata } from "next";
import { Cpu, Mic, Zap, Heart, Box, Palette } from "lucide-react";
import { APP_NAME } from "@/config/app.config";

export const metadata: Metadata = {
  title: "Features",
  description: `Explore ${APP_NAME} features: AI conversation, voice, emotions, and 3D character.`,
};

const FEATURES = [
  {
    icon: Cpu,
    title: "AI CONVERSATION",
    description:
      "Powered by the secure backend integrating Gemini and Groq. Every response is generated by advanced AI to feel natural and contextual.",
    tag: "AI",
  },
  {
    icon: Mic,
    title: "VOICE INTERACTION",
    description:
      "Speak to the companion using your device microphone. Natural voice input with real-time speech recognition — no typing required.",
    tag: "Voice",
  },
  {
    icon: Zap,
    title: "AI RESPONSE",
    description:
      "Gemini and Groq AI engines generate intelligent, context-aware responses that feel like a real conversation.",
    tag: "AI",
  },
  {
    icon: Heart,
    title: "EMOTIONAL REACTIONS",
    description:
      "The AI analyzes conversation tone and emotion. Your companion reacts with Happy, Excited, Surprised, or Neutral states.",
    tag: "Emotions",
  },
  {
    icon: Box,
    title: "3D CHARACTER",
    description:
      "A fully rendered 3D Spider-Man companion — not a boring chat bubble. Watch him animate, react, and feel alive.",
    tag: "3D",
  },
  {
    icon: Palette,
    title: "CUSTOM EXPERIENCE",
    description:
      "Custom Flutter UI designed specifically for this companion experience. Premium dark theme with red accent animations.",
    tag: "Flutter",
  },
];

export default function FeaturesPage() {
  return (
    <>
      {/* Hero */}
      <section className="pt-32 pb-20 px-6 text-center relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[300px] rounded-full bg-[#E31C25]/5 blur-[100px]" />
        </div>
        <p className="text-xs text-[#E31C25] tracking-widest uppercase mb-4 font-semibold z-10 relative">
          What it can do
        </p>
        <h1 className="text-5xl sm:text-6xl lg:text-7xl font-black tracking-tight mb-6 z-10 relative">
          FULL{" "}
          <span className="gradient-text-red">FEATURES</span>
        </h1>
        <p className="text-[#A0A0B0] max-w-lg mx-auto text-lg leading-relaxed z-10 relative">
          Every feature designed to make your companion feel real, responsive, and intelligent.
        </p>
      </section>

      {/* Feature grid */}
      <section className="max-w-6xl mx-auto px-6 pb-24">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((feature, i) => (
            <div
              key={feature.title}
              className="glass rounded-2xl p-7 hover:border-[#E31C25]/30 transition-all duration-300 group hover:-translate-y-1"
            >
              {/* Tag */}
              <div className="inline-flex items-center px-2.5 py-1 rounded-md bg-[#E31C25]/10 text-[#E31C25] text-[10px] font-bold tracking-widest uppercase mb-5">
                {feature.tag}
              </div>

              <div className="w-12 h-12 rounded-xl bg-[#E31C25]/10 flex items-center justify-center mb-5 group-hover:bg-[#E31C25]/20 transition-colors">
                <feature.icon size={22} className="text-[#E31C25]" />
              </div>

              <h3 className="text-white font-black tracking-wider text-sm mb-3">
                {feature.title}
              </h3>
              <p className="text-[#A0A0B0] text-sm leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA strip */}
      <section className="max-w-6xl mx-auto px-6 pb-24">
        <div className="glass rounded-3xl p-10 md:p-16 text-center relative overflow-hidden border border-[#E31C25]/10">
          <div className="absolute inset-0 pointer-events-none">
            <div className="absolute inset-0 bg-gradient-to-br from-[#E31C25]/5 to-transparent" />
          </div>
          <h2 className="text-3xl sm:text-4xl font-black tracking-tight mb-4 relative z-10">
            READY TO MEET{" "}
            <span className="gradient-text-red">YOUR COMPANION?</span>
          </h2>
          <p className="text-[#A0A0B0] mb-8 relative z-10">
            Download the app and experience all these features on your Android device.
          </p>
          <a
            href="/download"
            className="inline-flex items-center gap-2 px-8 py-3.5 rounded-full bg-[#E31C25] text-white font-bold tracking-wide hover:bg-[#FF4D55] transition-all hover:shadow-lg hover:shadow-red-500/25 hover:scale-105 relative z-10"
          >
            DOWNLOAD NOW
          </a>
        </div>
      </section>
    </>
  );
}
